export const tokens = {
  surfacePrimary: '#ffffff',
  surfaceSecondary: '#f6f6f7',
  surfaceTertiary: '#edeff0',
  borderSubtle: 'rgba(0,0,0,0.07)',
  borderDefault: 'rgba(0,0,0,0.12)',
  borderStrong: 'rgba(0,0,0,0.20)',
  textPrimary: '#111110',
  textSecondary: '#6b6b68',
  textTertiary: '#9b9b97',
  accentBase: '#248afd',
  accentLight: 'hsl(216, 50%, 92%)',
  accentHover: '#248afd',
  accentText: 'rgb(8, 43, 80)',
  fontDisplay: "'DM Sans', 'Helvetica Neue', sans-serif",
  fontBody: "'DM Sans', 'Helvetica Neue', sans-serif",
  radiusSm: '6px',
  radiusMd: '10px',
  radiusLg: '14px',
} as const
